---
- hosts: all
  become: yes
  tasks:
  - name: install nginx software
    apt:
      name: nginx
      state: present
  - name: Ensure nginx service is runnong
    service:
      name: nginx
      state: started
      enabled: yes
