---
- hosts: all
//if specified here, all plays will get executed with sudo user.
//if specified at play level, only that task gets executed with sudo previlages.
  become: yes
  tasks:
  - name: install tree software
    yum:
      name: httpd
      state: present
  - name: Ensure apache service is runnong
    service:
      name: httpd
      state: started
      enabled: yes