---
- hosts: appserver
//when we install something we have to use become to run with root previlages
  become: yes
  tasks:
  - name: install openjdk8
    yum:
      name: java-1.8.0-openjdk.x86_64
      state: present
  - name: install tomcat7
    yum:
      name: tomcat
      state: present
  - name: download jenkins to webapps
    get_url: 
      url: http://ftp-nyc.osuosl.org/pub/jenkins/war-stable/2.150.2/jenkins.war
      dest: /usr/share/tomcat/webapps/jenkins.war
  - name: enable and start tomcat
    service:
      name: tomcat
      state: started
      enabled: yes


